import {
	WebSocketGateway,
	SubscribeMessage,
	MessageBody,
	ConnectedSocket,
	OnGatewayConnection,
	OnGatewayDisconnect,
	OnGatewayInit,
	WebSocketServer,
} from "@nestjs/websockets";
import { WebsocketsService } from "./websockets.service";
import { Server, Socket } from "socket.io";

/* without specifying the port, it will use the default app port set in main.ts */
@WebSocketGateway({
	cors: {
		origin: "*",
		methods: ["GET", "POST"],
	},
})
export class WebsocketsGateway
	implements OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect
{
	constructor(private readonly websocketsService: WebsocketsService) {}
	@WebSocketServer()
	io!: Server;

	afterInit() {
		console.log("Websockets initialized");
	}

	handleConnection(client: any, ...args: any[]) {
		const { sockets } = this.io.sockets;
		/**
		 * here client.id s generated by socket.io and is unique for each connection,
		 * ensuring that each client can be individually identified and managed.
		 */
		console.log(`Client id: ${client.id} connected`);
		console.debug(`Number of connected clients: ${sockets.size}`);
	}

	handleDisconnect(client: any) {
		console.log(`Cliend id:${client.id} disconnected`);
	}

	/**
	 * listen to the `message` event emited by the client,
	 * and get the content from the body of the event.
	 */
	@SubscribeMessage("message")
	message(@MessageBody() body: any, @ConnectedSocket() clientSocket: Socket) {
		return this.websocketsService.message(body, clientSocket);
	}

	// @SubscribeMessage("createWebsocket")
	// create(@MessageBody() createWebsocketDto: CreateWebsocketDto) {
	// 	return this.websocketsService.create(createWebsocketDto);
	// }

	// @SubscribeMessage("findAllWebsockets")
	// findAll() {
	// 	return this.websocketsService.findAll();
	// }

	// @SubscribeMessage("findOneWebsocket")
	// findOne(@MessageBody() id: number) {
	// 	return this.websocketsService.findOne(id);
	// }

	// @SubscribeMessage("updateWebsocket")
	// update(@MessageBody() updateWebsocketDto: UpdateWebsocketDto) {
	// 	return this.websocketsService.update(
	// 		updateWebsocketDto.id,
	// 		updateWebsocketDto
	// 	);
	// }

	// @SubscribeMessage("removeWebsocket")
	// remove(@MessageBody() id: number) {
	// 	return this.websocketsService.remove(id);
	// }
}
