export const AUTH_ERRORS = {
  "AUTH.UNAUTHORIZED": 401,
  "AUTH.JWT_EXPIRED": 401,
  "AUTH.AUTH_PROVIDER_MISMATCH": 401,
  "AUTH.ACTOR_ID_MISSING": 401,
  "AUTH.ACTOR_TYPE_MISMATCH": 403,
  "AUTH.AUTH_IDENTITY_ID_MISSING": 401,
  "AUTH.FORBIDDEN": 403,
  "AUTH.SESSION_EXPIRED": 401,
  "AUTH.INVALID_TOKEN": 401,
} as const;
