export const PAYMENT_ERRORS = {
  "PAYMENT.PAYPAL_MISSING_ACCOUNT_HOLDER": 400,
  "PAYMENT.PAYPAL_MISSING_CONTEXT": 400,
  "PAYMENT.PAYPAL_MISSING_CUSTOMER": 400,
  "PAYMENT.PAYPAL_MISSING_CLIENT_SECRET": 400,
  "PAYMENT.PAYPAL_INVALID_ORDER_DATA": 400,
  "PAYMENT.PAYPAL_AUTHORIZATION_FAILED": 401,
  "PAYMENT.PAYPAL_MISSING_PAYMENT_ID": 400,
  "PAYMENT.PAYPAL_FAILED_TO_CREATE_ORDER": 500,
  "PAYMENT.PAYPAL_FAILED_TO_GENERATE_ACCESS_TOKEN": 500,
  "PAYMENT.PAYPAL_FAILED_TO_FETCH_ORDER": 500,
  "PAYMENT.PAYPAL_ORDER_CANNOT_BE_CAPTURED": 500,
} as const;
