export const PAYMENT_ERRORS = {
  "PAYMENT.MISSING_ACCOUNT_HOLDER": 400,
  "PAYMENT.MISSING_CONTEXT": 400,
  "PAYMENT.MISSING_CUSTOMER": 400,
  "PAYMENT.MISSING_API_KEY": 400,
  "PAYMENT.FAILED_TO_GENERATE_ACCESS_TOKEN": 500,
} as const;
